print('Complete the information')

First_name= input('First Name:')
Last_name= input('Last Name:')
#print(Last_name.title() + ',' + First_name.title())
Email_address= input('Email Address:')
Phone_number= input('Phone Number:')
Job_tittle= input('Job Tittle:')
#print(Job_tittle.title())
ID_number= input('ID Number:')

Hair_color= input('Hair Colour:')
Eye_color= input('Eye Color:')
print('The ID Card is ...........')
print(Last_name.title() + ',' + First_name.title())
print(Email_address.lower)
print(Phone_number)
print(Job_tittle.capitalize())
print(ID_number)